### ISSUE TITLE
Generate page hierarchies

### ISSUE THREAD

**Issue by flyinggrizzly** [sawhney17/logseq-schrodinger#30]
As noted in #29, I make use of Logseq's built-in hierarchy functionality, where creating a page like `[[Mr Color/GX/3 Red]]` creates a new page nested underneath parent pages. In this case, `[[Mr Color]]`, `[[Mr Color/GX]]`, and finally `[[Mr Color/GX/3 Red]]`. If the parent pages do not exist,they are added to the graph automatically, analogous to `mkdir -p mr-color/gx/3-red`.

Additionally, the generated pages are aware of their hierarchies:

- parents know about their children, and list them
- children know their path, and list it

Parent:

<img width="1512" alt="Screen Shot 2022-11-05 at 4 40 16 PM" src="https://user-images.githubusercontent.com/10967676/200131345-6fb98a42-79a0-4834-8477-6dea79f1036e.png">

(Grand) child:

<img width="1512" alt="Screen Shot 2022-11-05 at 4 40 31 PM" src="https://user-images.githubusercontent.com/10967676/200131362-25571e23-3d54-4bd7-801f-d847dc87b31d.png">

Schrodinger already creates these pages, but they lose awareness of their hierarchy links. It would be useful for these to be surfaceable in a published site link backlinks. Unfortunately, because they are not links present in the content, they do not get generated, and would require new work to do so.

Could these be added to page front matter? Maybe

```yaml
# Mr Color
hierarchy:
  - {{ ref . "pages/mr-color/gx" }}
  - {{ ref . "pages/mr-color/gx/3-red" }}
  - {{ ref . "pages/mr-color/gx/1-white" }}
  - {{ ref . "pages/mr-color/surfacer" }}
  - {{ ref . "pages/mr-color/surfacer/500" }}

# Mr Color/GX
hierarchy:
  - {{ ref . "pages/mr-color/gx/3-red" }}
  - {{ ref . "pages/mr-color/gx/1-white" }}

# Mr Color/GX/1 White
hierarchy:
  - {{ ref . "pages/mr-color/gx" }}
```
